name: 'CD — Publish'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.repository.fork == false
    name: Release Please
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: wellwelwel-bot
          changelog-path: 'CHANGELOG.md'

      - name: ➕ Actions - Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: ➕ Cache dependencies
        uses: actions/cache@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: 📦 Installing Dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm ci

      - name: 🚀 Building Action
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build
